config/routes.rb
Rails.application.routes.draw do
  resources :card_data
  devise_for :users
    root 'home#index'
    get 'card/index', to: 'card#index'
    get 'home/about', to: 'home#about'
    get 'home/search', to: 'home#search'
    get 'home/show', to: 'home#show'
    post 'home/search' => 'home/search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card_datum.rb
class CardDatum < ApplicationRecord
    belongs_to :user
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                   format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :card_datum
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/card_data_controller.rb
class CardDataController < ApplicationController
  before_action :set_card_datum, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]


  # GET /card_data
  # GET /card_data.json
  def index
    @card_data = CardDatum.all
  end

  # GET /card_data/1
  # GET /card_data/1.json
  def show
    @card_datum = CardDatum.find(params["id"])
  end

  # GET /card_data/new
  def new
    @card_datum = CardDatum.new
  end

  # GET /card_data/1/edit
  def edit
    @card_datum = CardDatum.find(params["id"])
  end

  # POST /card_data
  # POST /card_data.json
  def create
    @card_datum = CardDatum.new(card_datum_params)

    respond_to do |format|
      if @card_datum.save
        format.html { redirect_to @card_datum, notice: 'Card datum was successfully created.' }
        format.json { render :show, status: :created, location: @card_datum }
      else
        format.html { render :new }
        format.json { render json: @card_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /card_data/1
  # PATCH/PUT /card_data/1.json
  def update
    respond_to do |format|
      if @card_datum.update(card_datum_params)
        format.html { redirect_to @card_datum, notice: 'Card datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @card_datum }
      else
        format.html { render :edit }
        format.json { render json: @card_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /card_data/1
  # DELETE /card_data/1.json
  def destroy
    @card_datum.destroy
    respond_to do |format|
      format.html { redirect_to card_data_url, notice: 'Card datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card_datum
      @card_datum = CardDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_datum_params
      params.require(:card_datum).permit(:user_id, :name, :manaCost, :layout, :colors, :rarity, :text, :power, :toughness, :imageUrl)
    end

    def correct_user
        @correct = current_user.card_datum.find_by(id: params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
require 'will_paginate/array'

  def index
      require 'net/http'
      require 'json'
      @url = "https://api.magicthegathering.io/v1/cards"
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @cards = JSON.parse(@response)
    # @home = @card_info
    # .paginate(page: params[:page], per_page: 10)
  end

  def about
  end

  def show
  end

  def search
    @name = params[:name]
    require 'net/http'
    require 'json'
    @search_url = "https://api.magicthegathering.io/v1/cards/?name= " + @name.to_s
    @search_uri = URI(@search_url)
    @search_response = Net::HTTP.get(@search_uri)
    @search_cards = JSON.parse(@search_response)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_data_helper.rb
module CardDataHelper
end

app/helpers/card_infos_helper.rb
module CardInfosHelper
end

app/views/card_data/_form.html.erb
<%= form_with(model: card_datum, local: true) do |form| %>
  <% if card_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card_datum.errors.count, "error") %> prohibited this card_datum from being saved:</h2>

      <ul>
      <% card_datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.number_field :user_id, value: current_user.id, type: "hidden" %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :manaCost %>
    <%= form.number_field :manaCost, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :layout %>
    <%= form.text_field :layout, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :colors %>
    <%= form.text_field :colors, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :rarity %>
    <%= form.text_field :rarity, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :power %>
    <%= form.text_field :power, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :toughness %>
    <%= form.text_field :toughness, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :imageUrl %>
    <%= form.text_field :imageUrl, class: "form-control" %>
  </div>


<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/card_data/edit.html.erb
<h1>Editing Card Datum</h1>

<%= render 'form', card_datum: @card_datum %>

<%= link_to 'Show', @card_datum %> |
<%= link_to 'Back', card_data_path %>

app/views/card_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Cards Table</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Manacost</th>
      <th>Layout</th>
      <th>Colors</th>
       <th>Rarity</th>
       <th>Text</th>
       <th>Power</th>
       <th>Toughness</th>
       <th>imageUrl</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @card_data.each do |card_datum| %>
        <% if card_datum.user_id == current_user.id %>
      <tr>
        <td><%= card_datum.user_id %></td>
        <td><%= link_to card_datum.name,  card_datum %></td>
        <td><%= card_datum.manaCost %></td>
        <td><%= card_datum.layout %></td>
        <td><%= card_datum.colors %></td>
        <td><%= card_datum.rarity %></td>
        <td><%= card_datum.text %></td>
        <td><%= card_datum.power %></td>
        <td><%= card_datum.toughness %></td>
        <td><%= card_datum.imageUrl %></td>

       </tr>
      <% end %>
    <% end %>
  </tbody>
</table>




<br>

<%= link_to 'New Card', new_card_datum_path, class: "btn btn-danger" %>

app/views/card_data/new.html.erb
<h1>New Card Datum</h1>

<%= render 'form', card_datum: @card_datum %>

<%= link_to 'Back', card_data_path %>

app/views/card_data/show.html.erb
<p id="notice"><%= notice %></p>
<h1> <strong>Name:</strong>
 <%= @card_datum.name %></h1>
<div class="container">
<div class="row">
   <div class="col-sm">
     <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="<%= @card_datum.imageUrl %>" alt="Card image cap">
          <div class="card-body">

            <p>
              <strong>User:</strong>
              <%= @card_datum.user_id %>
            </p>

            <p>
              <strong>Manacost:</strong>
              <%= @card_datum.manaCost %>
            </p>

            <p>
              <strong>Layout:</strong>
              <%= @card_datum.layout %>
            </p>

            <p>
              <strong>Colors:</strong>
              <%= @card_datum.colors %>
            </p>
            <p>
              <strong>Rarity:</strong>
              <%= @card_datum.rarity %>
            </p>

            <p>
              <strong>Text:</strong>
              <%= @card_datum.text %>
            </p>

            <p>
              <strong>Power:</strong>
              <%= @card_datum.power %>
            </p>

            <p>
              <strong>Toughness:</strong>
              <%= @card_datum.toughness %>
            </p>


<%= link_to 'Edit', edit_card_datum_path(@card_datum) %> |
<%= link_to 'Back', card_data_path %> | <%= link_to 'Destroy', card_datum_path(@card_datum), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
</div>
</div>

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
        </button>
        <%= content_tag(:div, msg) %>
        </div>
        <% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Magic Cards</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a href ="https://kendrajmoore.github.io/magic_cards_app/#/" class="btn btn-primary">About</a>
        </li>
    <li class="nav-item">
        <%= link_to "Home", root_path, class: 'nav-link' %>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item">
        <%= link_to "MyCards", card_data_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
        <%= link_to "Add Card", new_card_datum_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
        <%= link_to "Log Out", destroy_user_session_path, class: 'nav-link' %>
    </li>
    <% else %>
    <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
    </li>
    <% end %>
    </ul>
    <%= form_tag home_search_path, :method => 'POST', class: 'form-inline my-2 my-lg-0' do %>
    <%= text_field_tag 'name', nil, placeholder: 'Card Name', class: 'form-control mr-sm-2' %>
    <%= submit_tag 'Search', class: 'btn btn-primary' %>
    <% end %>

  </div>
</nav>

app/views/home/about.html.erb
<h1>Hey</h1>

app/views/home/index.html.erb
<br>
<h1>Magic Cards App</h1>
<br>
<% @cards["cards"] %>
<div class="container">
<div class="row">
  <% for x in @cards["cards"] %>
   <div class="col-sm">
     <div class="card" style="width: 18rem;">
       <img class="card-img-top" src="<%= x["imageUrl"] %>" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title"><%= x["name"] %></h5>
            <p class="card-text"><%= x["text"] %></p>
            <p class="card-text">manaCost: <%=x["manaCost"] %></p>
            <p class="card-text">Layout: <%= x["layout"] %></p>
            <p class="card-text">Colors: <%= x["colors"] %></p>
            <p class="card-text">Rarity: <%= x["rarity"] %></p>
           <p class="card-text">Power: <%= x["power"] %></p>
           <p class="card-text">Toughness:<%= x["toughness"] %></p>
           <br>
           </div>
         </div>
        </div>
      <br>
       <br>
    <% end %>
   </div>
</div>
<br>
 <br>

app/views/home/search.html.erb
<br>
<h1>Search Results</h1>

<h5>Search term: <%= @name %></h5>
<% @search_cards["cards"] %>
<div class="container">
<div class="row">
<% for x in @search_cards["cards"] %>
<div class="col-sm">
  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="<%= x["imageUrl"] %>" alt src="https://images-na.ssl-images-amazon.com/images/I/51yRqvJKSdL.jpg">
    <h5 class="card-title"><%= x["name"] %></h5>
    <div class="card-body">
      <p class="card-text"><%= x["text"] %></p>
      <p class="card-text"><%=x["manaCost"] %></p>
      <p class="card-text"><%= x["layout"] %></p>
      <p class="card-text"><%= x["colors"] %></p>
      <p class="card-text"><%= x["rarity"] %></p>
     <p class="card-text"><%= x["power"] %></p>
     <p class="card-text"><%= x["toughness"] %></p>
     </div>
    </div>
    </div>
    <br>
    <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magic Cards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Inknut+Antiqua|Roboto" rel="stylesheet">
  </head>

  <body>

<%= render 'home/navbar' %>
<div class="container">
    <%= render 'home/flash' %>
    <%= yield %>

</div>
  </body>
</html>